### ISSUE TITLE
Why did you accepted my contributions and then reverted them?

### ISSUE THREAD

**Issue by wellingtoncosta** [jeancsanchez/Okhttp-Rest-Error-Interceptor#3]
I didn't understand exatcly why you accepted my contribuitions, and then reverted the changes. If you didn't like some change in your code or something like this, you could have commented about it in the pull request.

I'm just curious about this. I'm not sad or something like this.

**Comment by jeancsanchez** [comment]
@WellingtonCosta Oh man, don't get bored with me. I reversed because the PR is breaking the build on Jitpack, I'll investigate and fix that then merge again :)

**Comment by jeancsanchez** [comment]
To be more specific:
https://jitpack.io/com/github/jeancsanchez/okhttp-rest-error-interceptor/1.1.1/build.log
![Screen Shot 2019-04-08 at 06 48 55](https://user-images.githubusercontent.com/11152015/55715161-8b7cf980-59ca-11e9-905a-33036fc8b140.png)

I think is because of the android application plugin, but I'm not sure :/

**Comment by wellingtoncosta** [comment]
Yeah. The Jitpack build configuration must be configured to distribute it as a Java Library instead of an Android Library.

I can do this in my fork and then submit a new pull request.

**Comment by wellingtoncosta** [comment]
So, I configured the Jitpack build / distribution and, well, it worked like a charm.

See build.log: https://jitpack.io/com/github/WellingtonCosta/okhttp-rest-error-interceptor/-164febbaf3-1/build.log

**Comment by jeancsanchez** [comment]
@WellingtonCosta  send me the PR again, please!
